name          'jbouse-sks'
version       '0.1.4'
source        'git@github.com:UGNS/puppet-sks.git'
author        'jbouse'
license       'Apache License, Version 2.0'
summary       'Synchronizing Key Server (SKS) Puppet module'
description   'Configure and manage the Synchronizing Key Server (SKS)'
project_page  'https://github.com/UGNS/puppet-sks'
